//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.nbrm.mk/klservice/", ConfigurationName="ServiceReference1.KursSoap")]
    public interface KursSoap
    {
        
        // CODEGEN: Generating message contract since element name GetExchangeRateDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        ServiceReference1.GetExchangeRateDResponse GetExchangeRateD(ServiceReference1.GetExchangeRateDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRateDResponse> GetExchangeRateDAsync(ServiceReference1.GetExchangeRateDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        ServiceReference1.GetExchangeRateResponse GetExchangeRate(ServiceReference1.GetExchangeRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRateResponse> GetExchangeRateAsync(ServiceReference1.GetExchangeRateRequest request);
        
        // CODEGEN: Generating message contract since element name GetExchangeRatesDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        ServiceReference1.GetExchangeRatesDResponse GetExchangeRatesD(ServiceReference1.GetExchangeRatesDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRatesDResponse> GetExchangeRatesDAsync(ServiceReference1.GetExchangeRatesDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        ServiceReference1.GetExchangeRatesResponse GetExchangeRates(ServiceReference1.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRatesResponse> GetExchangeRatesAsync(ServiceReference1.GetExchangeRatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRateDRequestBody Body;
        
        public GetExchangeRateDRequest()
        {
        }
        
        public GetExchangeRateDRequest(ServiceReference1.GetExchangeRateDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRateDRequestBody()
        {
        }
        
        public GetExchangeRateDRequestBody(System.DateTime StartDate, System.DateTime EndDate)
        {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRateDResponseBody Body;
        
        public GetExchangeRateDResponse()
        {
        }
        
        public GetExchangeRateDResponse(ServiceReference1.GetExchangeRateDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateDResult;
        
        public GetExchangeRateDResponseBody()
        {
        }
        
        public GetExchangeRateDResponseBody(string GetExchangeRateDResult)
        {
            this.GetExchangeRateDResult = GetExchangeRateDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRate", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRateRequestBody Body;
        
        public GetExchangeRateRequest()
        {
        }
        
        public GetExchangeRateRequest(ServiceReference1.GetExchangeRateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRateRequestBody()
        {
        }
        
        public GetExchangeRateRequestBody(string StartDate, string EndDate)
        {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRateResponseBody Body;
        
        public GetExchangeRateResponse()
        {
        }
        
        public GetExchangeRateResponse(ServiceReference1.GetExchangeRateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateResult;
        
        public GetExchangeRateResponseBody()
        {
        }
        
        public GetExchangeRateResponseBody(string GetExchangeRateResult)
        {
            this.GetExchangeRateResult = GetExchangeRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRatesDRequestBody Body;
        
        public GetExchangeRatesDRequest()
        {
        }
        
        public GetExchangeRatesDRequest(ServiceReference1.GetExchangeRatesDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRatesDRequestBody()
        {
        }
        
        public GetExchangeRatesDRequestBody(System.DateTime StartDate, System.DateTime EndDate)
        {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRatesDResponseBody Body;
        
        public GetExchangeRatesDResponse()
        {
        }
        
        public GetExchangeRatesDResponse(ServiceReference1.GetExchangeRatesDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesDResult;
        
        public GetExchangeRatesDResponseBody()
        {
        }
        
        public GetExchangeRatesDResponseBody(string GetExchangeRatesDResult)
        {
            this.GetExchangeRatesDResult = GetExchangeRatesDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest()
        {
        }
        
        public GetExchangeRatesRequest(ServiceReference1.GetExchangeRatesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRatesRequestBody()
        {
        }
        
        public GetExchangeRatesRequestBody(string StartDate, string EndDate)
        {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public ServiceReference1.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse()
        {
        }
        
        public GetExchangeRatesResponse(ServiceReference1.GetExchangeRatesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody()
        {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult)
        {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface KursSoapChannel : ServiceReference1.KursSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class KursSoapClient : System.ServiceModel.ClientBase<ServiceReference1.KursSoap>, ServiceReference1.KursSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KursSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(KursSoapClient.GetBindingForEndpoint(endpointConfiguration), KursSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KursSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KursSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KursSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KursSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KursSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetExchangeRateDResponse ServiceReference1.KursSoap.GetExchangeRateD(ServiceReference1.GetExchangeRateDRequest request)
        {
            return base.Channel.GetExchangeRateD(request);
        }
        
        public string GetExchangeRateD(System.DateTime StartDate, System.DateTime EndDate)
        {
            ServiceReference1.GetExchangeRateDRequest inValue = new ServiceReference1.GetExchangeRateDRequest();
            inValue.Body = new ServiceReference1.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            ServiceReference1.GetExchangeRateDResponse retVal = ((ServiceReference1.KursSoap)(this)).GetExchangeRateD(inValue);
            return retVal.Body.GetExchangeRateDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRateDResponse> ServiceReference1.KursSoap.GetExchangeRateDAsync(ServiceReference1.GetExchangeRateDRequest request)
        {
            return base.Channel.GetExchangeRateDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetExchangeRateDResponse> GetExchangeRateDAsync(System.DateTime StartDate, System.DateTime EndDate)
        {
            ServiceReference1.GetExchangeRateDRequest inValue = new ServiceReference1.GetExchangeRateDRequest();
            inValue.Body = new ServiceReference1.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((ServiceReference1.KursSoap)(this)).GetExchangeRateDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetExchangeRateResponse ServiceReference1.KursSoap.GetExchangeRate(ServiceReference1.GetExchangeRateRequest request)
        {
            return base.Channel.GetExchangeRate(request);
        }
        
        public string GetExchangeRate(string StartDate, string EndDate)
        {
            ServiceReference1.GetExchangeRateRequest inValue = new ServiceReference1.GetExchangeRateRequest();
            inValue.Body = new ServiceReference1.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            ServiceReference1.GetExchangeRateResponse retVal = ((ServiceReference1.KursSoap)(this)).GetExchangeRate(inValue);
            return retVal.Body.GetExchangeRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRateResponse> ServiceReference1.KursSoap.GetExchangeRateAsync(ServiceReference1.GetExchangeRateRequest request)
        {
            return base.Channel.GetExchangeRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetExchangeRateResponse> GetExchangeRateAsync(string StartDate, string EndDate)
        {
            ServiceReference1.GetExchangeRateRequest inValue = new ServiceReference1.GetExchangeRateRequest();
            inValue.Body = new ServiceReference1.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((ServiceReference1.KursSoap)(this)).GetExchangeRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetExchangeRatesDResponse ServiceReference1.KursSoap.GetExchangeRatesD(ServiceReference1.GetExchangeRatesDRequest request)
        {
            return base.Channel.GetExchangeRatesD(request);
        }
        
        public string GetExchangeRatesD(System.DateTime StartDate, System.DateTime EndDate)
        {
            ServiceReference1.GetExchangeRatesDRequest inValue = new ServiceReference1.GetExchangeRatesDRequest();
            inValue.Body = new ServiceReference1.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            ServiceReference1.GetExchangeRatesDResponse retVal = ((ServiceReference1.KursSoap)(this)).GetExchangeRatesD(inValue);
            return retVal.Body.GetExchangeRatesDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRatesDResponse> ServiceReference1.KursSoap.GetExchangeRatesDAsync(ServiceReference1.GetExchangeRatesDRequest request)
        {
            return base.Channel.GetExchangeRatesDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetExchangeRatesDResponse> GetExchangeRatesDAsync(System.DateTime StartDate, System.DateTime EndDate)
        {
            ServiceReference1.GetExchangeRatesDRequest inValue = new ServiceReference1.GetExchangeRatesDRequest();
            inValue.Body = new ServiceReference1.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((ServiceReference1.KursSoap)(this)).GetExchangeRatesDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetExchangeRatesResponse ServiceReference1.KursSoap.GetExchangeRates(ServiceReference1.GetExchangeRatesRequest request)
        {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string StartDate, string EndDate)
        {
            ServiceReference1.GetExchangeRatesRequest inValue = new ServiceReference1.GetExchangeRatesRequest();
            inValue.Body = new ServiceReference1.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            ServiceReference1.GetExchangeRatesResponse retVal = ((ServiceReference1.KursSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetExchangeRatesResponse> ServiceReference1.KursSoap.GetExchangeRatesAsync(ServiceReference1.GetExchangeRatesRequest request)
        {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetExchangeRatesResponse> GetExchangeRatesAsync(string StartDate, string EndDate)
        {
            ServiceReference1.GetExchangeRatesRequest inValue = new ServiceReference1.GetExchangeRatesRequest();
            inValue.Body = new ServiceReference1.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((ServiceReference1.KursSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KursSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.KursSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KursSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.nbrm.mk/klservice/kurs.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.KursSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.nbrm.mk/klservice/kurs.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            KursSoap,
            
            KursSoap12,
        }
    }
}
